# Generated by Django 3.1.5 on 2021-03-15 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('IncomeExpenditure', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='spent_on',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expenditureType', to='IncomeExpenditure.expendituretype'),
        ),
        migrations.AlterField(
            model_name='income',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incomeSource', to='IncomeExpenditure.incomesource'),
        ),
    ]
